---
- name: Restart AdGuard Home service
  ansible.builtin.command:
    cmd: docker restart adguard-{{ inventory_hostname }}

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: ansible_service_mgr == "systemd"
